language: node_js
node_js:
  - stable
cache: yarn
script:
  - yarn install
  - yarn test
  - yarn build
after_success:
  - yarn global add firebase-tools
  - firebase deploy --token "$FIREBASE_TOKEN"
