language: node_js
node_js:
  - 9
cache: yarn
script:
  - (cd functions && yarn install)
  - yarn install
  - yarn test
  - yarn build
deploy:
  provider: script
  script:
    - yarn global add firebase-tools
    - firebase deploy --token "$FIREBASE_TOKEN"
