language: node_js
cache: yarn
node_js:
   -  stable
script:
   - yarn install
  - yarn test
  - yarn build
after_success:
  - yarn global add firebase-tools
   - firebase deploy --token "$FIREBASE_TOKEN"
